*******************************************
* ASSIST09 MONITOR SWI FUNCTIONS
* THE FOLLOWING EQUATES DEFINE FUNCTIONS PROVIDED
* BY THE ASSIST09 MONITOR VIA THE SWI INSTRUCTION.
******************************************
INCHNP		EQU	0		; INPUT CHAR IN A REG - NO PARITY
OUTCH		EQU	1		; OUTPUT CHAR FROM A REG
PDATA1		EQU	2		; OUTPUT STRING
PDATA		EQU	3		; OUTPUT CR/LF THEN STRING
OUT2HS		EQU	4		; OUTPUT TWO HEX AND SPACE
OUT4HS		EQU	5		; OUTPUT FOUR HEX AND SPACE
PCRLF		EQU	6		; OUTPUT CR/LF
PSPACE		EQU	7		; OUTPUT A SPACE
MONITR		EQU	8		; ENTER ASSIST09 MONITOR
VCTRSW		EQU	9		; VECTOR EXAMINE/SWITCH
BRKPT		EQU	10		; USER PROGRAM BREAKPOINT
PAUSE		EQU	11		; TASK PAUSE FUNCTION
NUMFUN		EQU	11		; NUMBER OF AVAILABLE FUNCTIONS
